#!/bin/bash
#
# Serves as a drop-in replacement for groovy.
# Downloads, caches and runs groovy with the given parameter.
#
# The thinking is that this file is added to git along with any groovy scripts, thus making sure that
# anyone needing to run the scripts can do so without (1) installing groovy, and (2) worrying about
# using a different groovy version.
#
# Do note that java is still required.
#
# Author: Knut Saua Mathiesen - github.com/ksaua - knut@saua.no
cache_dir=~/.groovy/bootstrapper
groovy_version="2.4.6"
java_version=`java -version 2>&1 | awk -F '"' '/version/ {print $2}'`

# Groovy and the dependencies needed to run groovy. This is by no means a complete list.
dependencies=(\
"org.codehaus.groovy:groovy-all:$groovy_version"
"commons-cli:commons-cli:1.3.1"
"commons-io:commons-io:2.5"
"org.apache.ivy:ivy:2.4.0"
"commons-httpclient:commons-httpclient:3.1"
)

# Create cache dir if it does not exist
if [ ! -f $cache_dir ]; then
    mkdir -p $cache_dir
fi

read -r -d '' TAG <<'EOF'
`
   _____                              _                 _       _
  / ____|                            | |               | |     | |
 | |  __ _ __ ___   _____   ___   _  | |__   ___   ___ | |_ ___| |_ _ __ __ _ _ __  _ __   ___ _ __
 | | |_ | '__/ _ \ / _ \ \ / / | | | | '_ \ / _ \ / _ \| __/ __| __| '__/ _` | '_ \| '_ \ / _ \ '__|
 | |__| | | | (_) | (_) \ V /| |_| | | |_) | (_) | (_) | |_\__ \ |_| | | (_| | |_) | |_) |  __/ |
  \_____|_|  \___/ \___/ \_/  \__, | |_.__/ \___/ \___/ \__|___/\__|_|  \__,_| .__/| .__/ \___|_|
                               __/ |                                         | |   | |
                              |___/                                          |_|   |_|              
EOF
echo "$TAG"
echo "   Version: 0.1"
echo "   Groovy version: $groovy_version"
echo "   Java version: $java_version"
echo ""

echo ":: checking wrapper dependencies"
classpath="."
for dependency in ${dependencies[*]}
do
    split=(${dependency//:/ })
    group=${split[0]}
    module=${split[1]}
    version=${split[2]}

    jar_name="$module-$version.jar"
    group_url=`echo $group | sed -r 's/\./\//g'`
    local_jar_file=$cache_dir/$jar_name

    classpath="$local_jar_file:$classpath"
    if [ ! -f $local_jar_file ]; then
        jar_url=http://central.maven.org/maven2/$group_url/$module/$version/$jar_name
        echo "Downloading $module"
        curl -o $local_jar_file $jar_url || exit 1
    fi
done

echo ":: running groovy $@"

#extra_params="-Dgroovy.grape.report.downloads=true"
java -noverify -cp $classpath groovy.ui.GroovyMain $extra_params "$@"

